#!/bin/bash
# Cloudflare Pages Deploy via GitHub

echo "=== Cloudflare Pages Deployment ==="
echo ""
echo "Option 1: Direct Upload (recommended)"
echo "1. Go to https://dash.cloudflare.com/"
echo "2. Go to Workers & Pages > Create > Pages"
echo "3. Connect to Git > Select GitHub > absolutus-aeternus/Platform"
echo "4. Set build settings:"
echo "   - Framework preset: None"
echo "   - Build command: npm run build"
echo "   - Build output directory: dist"
echo "5. Click Save and Deploy"
echo ""
echo "Option 2: Direct Upload via Wrangler"
echo "1. Run: npx wrangler login"
echo "2. Run: npx wrangler pages deploy dist --project-name=tk-shop-platform"
echo ""
echo "Option 3: Manual Upload"
echo "1. Go to https://dash.cloudflare.com/"
echo "2. Go to Workers & Pages > Create > Pages"
echo "3. Upload assets > Select dist/ folder"
echo ""
echo "Your dist/ folder is ready with $(ls dist/ | wc -l) files"
