name = "alliancehub-api"
main = "src/worker/index.js"
compatibility_date = "2024-01-01"

[vars]
VITE_SUPABASE_URL = "https://cfzmdvymqqnrzrytcrie.supabase.co"
VITE_R2_PUBLIC_URL = "/api/file"
VITE_R2_BUCKET_NAME = "alliancehub"
B2_BUCKET_NAME = "alliancehub"
B2_BUCKET_ID = "c8d3e82c42680279a70b031b"
VITE_ALGOLIA_APP_ID = "GLRKXLGDD9"
VITE_ALGOLIA_SEARCH_KEY = "383df1809e4a5bed8888e8cf6726b38e"
CRON_JOB_TOKEN = "mLSjn9fbD5GlLOHcE/hc+yJKu0AQtsvOwaetnklAgqA="

[triggers]
crons = ["0 18 * * *"]
